language: java, node_js
notifications:
  email:
    recipients:
      - pacman@T-Mobile.com
    on_success: never # default: change
    on_failure: always # default: always
node_js:
- "node"

# If your build needs more advanced behavior, see detailed Travis CI instructions:
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
